# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.9

WORKDIR /app
COPY . /app

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
# Set PATH
ENV PATH "/root/.local/bin:$PATH"

# Install depdendencies
RUN poetry install

# Run app
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]