[tool.poetry]
name = "de-study"
version = "0.1.0"
description = ""
authors = ["Sangmin Hwang <hwsmin920@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
